const stadiums = [
  {
    id: 219,
    country_id: 98,
    city_id: 68322,
    name: "McDiarmid Park",
    address: "Crieff Road",
    zipcode: null,
    latitude: "56.409686",
    longitude: "-3.476928",
    capacity: 10696,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/27/219.png",
    city_name: "Perth",
    surface: "grass",
    national_team: false,
  },
  {
    id: 245,
    country_id: 462,
    city_id: 28100,
    name: "Falkirk Community Stadium",
    address: "Westfield",
    zipcode: null,
    latitude: "56.005394",
    longitude: "-3.752637",
    capacity: 7937,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/21/245.png",
    city_name: "Falkirk",
    surface: "artificial turf",
    national_team: false,
  },
  {
    id: 342,
    country_id: 320,
    city_id: 37168,
    name: "MCH Arena",
    address: "Kaj Zartows Vej 5",
    zipcode: null,
    latitude: "56.116910",
    longitude: "8.951817",
    capacity: 11809,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/22/342.png",
    city_name: "Herning",
    surface: "grass",
    national_team: false,
  },
  {
    id: 390,
    country_id: 320,
    city_id: 52,
    name: "Nordjyske Arena",
    address: "Harald Jensens Vej 9",
    zipcode: null,
    latitude: "47.822778",
    longitude: "16.255278",
    capacity: 4290,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/6/390.png",
    city_name: "Aalborg",
    surface: "grass",
    national_team: false,
  },
  {
    id: 618,
    country_id: 320,
    city_id: 27321,
    name: "Blue Water Arena",
    address: "Gl. Vardevej 82",
    zipcode: null,
    latitude: "55.483044",
    longitude: " 8.438862",
    capacity: 2549,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/10/618.png",
    city_name: "Esbjerg",
    surface: "grass",
    national_team: false,
  },
  {
    id: 706,
    country_id: 462,
    city_id: 24803,
    name: "Palmerston Park",
    address: "Terregles Street",
    zipcode: null,
    latitude: "55.069767",
    longitude: "-3.624944",
    capacity: 8690,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/2/706.png",
    city_name: "Dumfries",
    surface: "artificial turf",
    national_team: false,
  },
  {
    id: 827,
    country_id: 462,
    city_id: 3446,
    name: "Gayfield Park",
    address: "Queens Drive",
    zipcode: null,
    latitude: "56.552269",
    longitude: "-2.591519",
    capacity: 5900,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/27/827.png",
    city_name: "Arbroath",
    surface: "grass",
    national_team: false,
  },
  {
    id: 849,
    country_id: 320,
    city_id: 37866,
    name: "DS Arena",
    address: "Amerikavej 9A",
    zipcode: null,
    latitude: "56.634967",
    longitude: "9.819800",
    capacity: 10700,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/17/849.png",
    city_name: "Hobro",
    surface: "grass",
    national_team: false,
  },
  {
    id: 914,
    country_id: 320,
    city_id: 64586,
    name: "EWII Park",
    address: "Højstrupvej 7B",
    zipcode: null,
    latitude: "55.38911",
    longitude: "10.38875",
    capacity: 15790,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/18/914.png",
    city_name: "Odense",
    surface: "grass",
    national_team: false,
  },
  {
    id: 1414,
    country_id: 320,
    city_id: 73074,
    name: "BioNutria Park Randers",
    address: "Viborgvej 92a",
    zipcode: null,
    latitude: "56.465955",
    longitude: "10.010346",
    capacity: 12000,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/6/1414.png",
    city_name: "Randers",
    surface: "grass",
    national_team: false,
  },
  {
    id: 1436,
    country_id: 320,
    city_id: 28321,
    name: "Right to Dream Park",
    address: "Idrætsvænget 2",
    zipcode: null,
    latitude: "55.816125",
    longitude: "12.352792",
    capacity: 10300,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/28/1436.png",
    city_name: "Farum",
    surface: "grass",
    national_team: false,
  },
  {
    id: 1467,
    country_id: 320,
    city_id: 94694,
    name: "Energi Viborg Arena",
    address: "Stadion Allé 7",
    zipcode: null,
    latitude: "56.456100",
    longitude: "9.401849",
    capacity: 9566,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/27/1467.png",
    city_name: "Viborg",
    surface: "grass",
    national_team: false,
  },
  {
    id: 1576,
    country_id: null,
    city_id: null,
    name: "Lyngby Stadion",
    address: "Lundtoftevej 53",
    zipcode: null,
    latitude: "55.781454",
    longitude: "12.505519",
    capacity: 10000,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/8/1576.png",
    city_name: "Lyngby",
    surface: "grass",
    national_team: false,
  },
  {
    id: 1608,
    country_id: null,
    city_id: null,
    name: "Hjørring Stadion",
    address: "Tørholmsvej 10",
    zipcode: null,
    latitude: "57.45924",
    longitude: "9.99470",
    capacity: 7500,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/8/1608.png",
    city_name: "Hjørring",
    surface: "grass",
    national_team: false,
  },
  {
    id: 1708,
    country_id: 320,
    city_id: 3669,
    name: "Ceres Park",
    address: "Stadion Allé 70",
    zipcode: null,
    latitude: "56.132030",
    longitude: "10.196503",
    capacity: 19433,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/12/1708.png",
    city_name: "Århus",
    surface: "grass",
    national_team: false,
  },
  {
    id: 4832,
    country_id: 320,
    city_id: 94178,
    name: "Vejle Stadion",
    address: "Roms Hule 3",
    zipcode: null,
    latitude: "55.713774",
    longitude: "9.556805",
    capacity: 10250,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/0/4832.png",
    city_name: "Vejle",
    surface: "grass",
    national_team: false,
  },
  {
    id: 5599,
    country_id: 320,
    city_id: 84098,
    name: "Harboe Arena Slagelse",
    address: "Parkvej 41 / Fælledvej 2B",
    zipcode: null,
    latitude: "55.400546",
    longitude: "11.364261",
    capacity: 3300,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/31/5599.png",
    city_name: "Slagelse",
    surface: "grass",
    national_team: false,
  },
  {
    id: 5602,
    country_id: null,
    city_id: null,
    name: "Helsingør Stadion",
    address: "Gl. Hellebækvej 63",
    zipcode: null,
    latitude: "56.045426",
    longitude: "12.586157",
    capacity: 4500,
    image_path: null,
    city_name: "Helsingør",
    surface: "grass",
    national_team: false,
  },
  {
    id: 5603,
    country_id: null,
    city_id: null,
    name: "TRE-FOR Park",
    address: null,
    zipcode: null,
    latitude: "40.64754",
    longitude: "-111.49181",
    capacity: 15790,
    image_path: "https://cdn.sportmonks.com/images/soccer/venues/3/5603.png",
    city_name: "TRE-FOR Park",
    surface: "grass",
    national_team: false,
  },
  {
    id: 5619,
    country_id: 320,
    city_id: 28321,
    name: "Farum Park",
    address: null,
    zipcode: null,
    latitude: "55.8160737",
    longitude: "12.3530585",
    capacity: 10100,
    image_path: null,
    city_name: "Farum",
    surface: null,
    national_team: false,
  },
  {
    id: 5621,
    country_id: 320,
    city_id: 35072,
    name: "Haderslev Fodboldstadion",
    address: null,
    zipcode: null,
    latitude: "55.24281",
    longitude: "9.51646",
    capacity: null,
    image_path: null,
    city_name: "Haderslev",
    surface: null,
    national_team: false,
  },
  {
    id: 5622,
    country_id: null,
    city_id: null,
    name: "SEAS-NVE Park",
    address: null,
    zipcode: null,
    latitude: "55.41850",
    longitude: "12.14868",
    capacity: null,
    image_path: null,
    city_name: "Herfølge",
    surface: null,
    national_team: false,
  },
  {
    id: 5624,
    country_id: null,
    city_id: null,
    name: "NRGi Park",
    address: null,
    zipcode: null,
    latitude: "56.15587",
    longitude: "10.20058",
    capacity: null,
    image_path: null,
    city_name: "Århus C",
    surface: null,
    national_team: false,
  },
  {
    id: 5626,
    country_id: null,
    city_id: null,
    name: "AutoC Park Randers",
    address: null,
    zipcode: null,
    latitude: "56.47607",
    longitude: "9.97680",
    capacity: null,
    image_path: null,
    city_name: "Randers NV",
    surface: null,
    national_team: false,
  },
  {
    id: 5629,
    country_id: 320,
    city_id: 83512,
    name: "Silkeborg Stadion",
    address: null,
    zipcode: null,
    latitude: "56.17343",
    longitude: "9.55549",
    capacity: null,
    image_path: null,
    city_name: "Silkeborg",
    surface: null,
    national_team: false,
  },
]

export default stadiums
